# PROJECT ARCHITECTURE

Player Statistics Dataset
            
            ↓
            
Data Cleaning & Feature Engineering
            
            ↓
            
EDA & Visualization
            
            ↓
            
Talent Score Calculation
            
            ↓
            
Machine Learning Model
            
            ↓
            
Future Potential Prediction
            
            ↓
            
Auction Value Estimation
            
            ↓
            
Streamlit Dashboard

# Input Features

Batting

Matches

Innings

Runs

Average

Strike Rate

50s

100s

Highest Score

# Bowling

Wickets

Economy

Bowling Average

Strike Rate

Maidens

# Fielding

Catches

Run Outs

Stumpings

# Fitness

Age

Fitness Score


# Output

## Talent Score

0 - 40     → Beginner

41 - 60    → Promising

61 - 80    → Future Star

81 - 100   → Elite Talent

## Future Potential

Low

Medium

High

Very High

## Estimated Auction Value

₹20 Lakhs

₹50 Lakhs

₹1 Crore

₹5 Crores

In [45]:
import os

print(os.getcwd())

C:\Users\udayd\AI_Sports_Talent_Scout\notebooks

In [46]:
import os

print(os.path.exists("data"))

True

In [47]:
import os

os.makedirs("data", exist_ok=True)

print("Data folder created successfully!")

Data folder created successfully!

In [48]:
import os

print(os.path.exists("data"))

True

In [49]:
df.to_csv("data/players.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [50]:
df.to_csv("data/players.csv", index=False)

In [51]:
df.to_csv("players.csv", index=False)

In [52]:
import os

print(os.listdir())

['.ipynb_checkpoints', 'data', 'DATASET_GENERATION.ipynb', 'players.csv', 'Sports_scout.ipynb', 'Untitled.ipynb']

In [53]:
print(os.listdir("data"))

['players.csv']

In [54]:
df.to_csv("players.csv", index=False)

# Complete Dataset Generator

In [55]:
import pandas as pd
import numpy as np
import random
import os
from sklearn.preprocessing import MinMaxScaler

# Reproducibility
random.seed(42)
np.random.seed(42)

# Number of players
n_players = 3000

roles = ["Batter", "Bowler", "All-Rounder", "Wicketkeeper"]

data = []

for i in range(n_players):

    # Basic Information
    player_id = i + 1
    age = random.randint(18, 35)
    role = random.choice(roles)
    matches = random.randint(10, 250)

    # -------------------------
    # Role-Based Statistics
    # -------------------------

    if role == "Batter":

        runs = random.randint(3000, 8000)
        batting_average = round(random.uniform(35, 65), 2)
        strike_rate = round(random.uniform(120, 190), 2)

        fifties = random.randint(10, 50)
        hundreds = random.randint(1, 20)

        wickets = random.randint(0, 30)
        economy = round(random.uniform(6, 10), 2)

        catches = random.randint(10, 80)

    elif role == "Bowler":

        runs = random.randint(0, 1500)
        batting_average = round(random.uniform(10, 30), 2)
        strike_rate = round(random.uniform(70, 120), 2)

        fifties = random.randint(0, 5)
        hundreds = random.randint(0, 1)

        wickets = random.randint(100, 350)
        economy = round(random.uniform(4, 8), 2)

        catches = random.randint(5, 50)

    elif role == "All-Rounder":

        runs = random.randint(1500, 5000)
        batting_average = round(random.uniform(25, 50), 2)
        strike_rate = round(random.uniform(100, 160), 2)

        fifties = random.randint(5, 30)
        hundreds = random.randint(0, 10)

        wickets = random.randint(50, 250)
        economy = round(random.uniform(4, 8), 2)

        catches = random.randint(10, 100)

    else:  # Wicketkeeper

        runs = random.randint(2000, 7000)
        batting_average = round(random.uniform(25, 55), 2)
        strike_rate = round(random.uniform(100, 170), 2)

        fifties = random.randint(5, 40)
        hundreds = random.randint(0, 15)

        wickets = random.randint(0, 10)
        economy = round(random.uniform(6, 10), 2)

        catches = random.randint(50, 150)

    # -------------------------
    # Age-Based Fitness
    # -------------------------

    if age <= 24:
        fitness_score = random.randint(80, 100)

    elif age <= 30:
        fitness_score = random.randint(70, 95)

    else:
        fitness_score = random.randint(60, 90)

    # -------------------------
    # Talent Score Components
    # -------------------------

    batting_impact = (
        runs * 0.002
        + batting_average * 0.30
        + strike_rate * 0.15
    )

    bowling_impact = (
        wickets * 0.08
        + (10 - economy) * 2
    )

    fielding_impact = catches * 0.10

    fitness_impact = fitness_score * 0.25

    raw_score = (
        batting_impact
        + bowling_impact
        + fielding_impact
        + fitness_impact
    )

    data.append([
        player_id,
        age,
        role,
        matches,
        runs,
        batting_average,
        strike_rate,
        fifties,
        hundreds,
        wickets,
        economy,
        catches,
        fitness_score,
        raw_score
    ])

# -------------------------
# Create DataFrame
# -------------------------

columns = [
    "player_id",
    "age",
    "role",
    "matches",
    "runs",
    "batting_average",
    "strike_rate",
    "fifties",
    "hundreds",
    "wickets",
    "economy",
    "catches",
    "fitness_score",
    "raw_score"
]

df = pd.DataFrame(data, columns=columns)

# -------------------------
# Talent Score (0-100)
# -------------------------

scaler = MinMaxScaler()

df["talent_score"] = scaler.fit_transform(
    df[["raw_score"]]
) * 100

df["talent_score"] = df["talent_score"].round(2)

# -------------------------
# Future Potential
# -------------------------

def future_potential(score):

    if score >= 80:
        return "Elite"

    elif score >= 60:
        return "High"

    elif score >= 40:
        return "Medium"

    else:
        return "Low"

df["future_potential"] = df["talent_score"].apply(
    future_potential
)

# -------------------------
# Auction Value (Crores)
# -------------------------

df["auction_value_cr"] = (
    df["talent_score"] * 0.12
    + df["batting_average"] * 0.05
    + df["wickets"] * 0.02
    + np.random.normal(0, 0.5, len(df))
)

df["auction_value_cr"] = (
    df["auction_value_cr"]
    .clip(lower=0.2)
    .round(2)
)

# -------------------------
# Save Dataset
# -------------------------

df.to_csv("players.csv", index=False)

print("Dataset Created Successfully!")
print("\nShape:", df.shape)

print("\nFuture Potential Distribution:")
print(df["future_potential"].value_counts())

print("\nFirst 5 Rows:")
print(df.head())

Dataset Created Successfully!

Shape: (3000, 17)

Future Potential Distribution:
future_potential
Medium    1446
High       751
Low        722
Elite       81
Name: count, dtype: int64

First 5 Rows:
   player_id  age          role  matches  runs  batting_average  strike_rate  \
0          1   21        Batter      199  5253            42.35       129.77
1          2   20        Bowler       69  1034            22.04        98.06
2          3   23  Wicketkeeper       97  4276            29.66       167.00
3          4   26        Batter      196  6763            51.09       188.12
4          5   24        Batter       21  4866            58.19       188.97

   fifties  hundreds  wickets  economy  catches  fitness_score  raw_score  \
0       16        18        2     8.36       14             80    67.5165
1        5         1      156     5.80       22             80    66.4690
2       26         3        1     7.52       95             91    79.7900
3       34         3       17     7.17       56             88    91.6910
4       24         4       12     7.11       56             85    89.1245

   talent_score future_potential  auction_value_cr
0         31.46              Low              6.18
1         29.48              Low              7.69
2         54.73           Medium              8.39
3         77.28             High             12.93
4         72.42             High             11.72

In [56]:
print(df.shape)
print(df.head())
print(df["future_potential"].value_counts())

(3000, 17)
   player_id  age          role  matches  runs  batting_average  strike_rate  \
0          1   21        Batter      199  5253            42.35       129.77
1          2   20        Bowler       69  1034            22.04        98.06
2          3   23  Wicketkeeper       97  4276            29.66       167.00
3          4   26        Batter      196  6763            51.09       188.12
4          5   24        Batter       21  4866            58.19       188.97

   fifties  hundreds  wickets  economy  catches  fitness_score  raw_score  \
0       16        18        2     8.36       14             80    67.5165
1        5         1      156     5.80       22             80    66.4690
2       26         3        1     7.52       95             91    79.7900
3       34         3       17     7.17       56             88    91.6910
4       24         4       12     7.11       56             85    89.1245

   talent_score future_potential  auction_value_cr
0         31.46              Low              6.18
1         29.48              Low              7.69
2         54.73           Medium              8.39
3         77.28             High             12.93
4         72.42             High             11.72
future_potential
Medium    1446
High       751
Low        722
Elite       81
Name: count, dtype: int64

In [57]:
df

,player_id,age,role,matches,runs,batting_average,strike_rate,fifties,hundreds,wickets,economy,catches,fitness_score,raw_score,talent_score,future_potential,auction_value_cr
0,1,21,Batter,199,5253,42.35,129.77,16,18,2,8.36,14,80,67.5165,31.46,Low,6.18
1,2,20,Bowler,69,1034,22.04,98.06,5,1,156,5.80,22,80,66.4690,29.48,Low,7.69
2,3,23,Wicketkeeper,97,4276,29.66,167.00,26,3,1,7.52,95,91,79.7900,54.73,Medium,8.39
3,4,26,Batter,196,6763,51.09,188.12,34,3,17,7.17,56,88,91.6910,77.28,High,12.93
4,5,24,Batter,21,4866,58.19,188.97,24,4,12,7.11,56,85,89.1245,72.42,High,11.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,19,Batter,33,6645,35.38,158.93,16,5,21,8.85,46,100,81.3235,57.63,Medium,9.14
2996,2997,28,Wicketkeeper,113,2613,47.13,116.76,22,9,8,7.13,139,79,76.9090,49.26,Medium,8.56
2997,2998,23,Bowler,90,1461,17.01,77.49,4,0,263,4.85,15,97,76.7385,48.94,Medium,11.36
2998,2999,33,All-Rounder,230,3160,41.46,134.43,22,1,218,4.83,27,73,87.6525,69.63,High,14.96
2999,3000,28,Wicketkeeper,80,5738,53.52,133.06,10,10,8,8.24,143,93,89.2010,72.56,High,11.47

In [58]:
print(os.getcwd())

C:\Users\udayd\AI_Sports_Talent_Scout\notebooks

In [59]:
print(df["future_potential"].value_counts())

future_potential
Medium    1446
High       751
Low        722
Elite       81
Name: count, dtype: int64

In [60]:
print(df["future_potential"].value_counts())

future_potential
Medium    1446
High       751
Low        722
Elite       81
Name: count, dtype: int64

In [61]:
df.head()

,player_id,age,role,matches,runs,batting_average,strike_rate,fifties,hundreds,wickets,economy,catches,fitness_score,raw_score,talent_score,future_potential,auction_value_cr
0,1,21,Batter,199,5253,42.35,129.77,16,18,2,8.36,14,80,67.5165,31.46,Low,6.18
1,2,20,Bowler,69,1034,22.04,98.06,5,1,156,5.80,22,80,66.4690,29.48,Low,7.69
2,3,23,Wicketkeeper,97,4276,29.66,167.00,26,3,1,7.52,95,91,79.7900,54.73,Medium,8.39
3,4,26,Batter,196,6763,51.09,188.12,34,3,17,7.17,56,88,91.6910,77.28,High,12.93
4,5,24,Batter,21,4866,58.19,188.97,24,4,12,7.11,56,85,89.1245,72.42,High,11.72

In [62]:
df["role"].value_counts()

role
Bowler          771
Wicketkeeper    755
Batter          744
All-Rounder     730
Name: count, dtype: int64

In [63]:
df["future_potential"].value_counts()

future_potential
Medium    1446
High       751
Low        722
Elite       81
Name: count, dtype: int64